language: python
python:
- 2.6
- 2.7
script:
- pip install git+git://github.com/abstractfactory/pyblish-nuke.git
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: A92VrxSdgXTePM9mEBTgzJ3TAJkhl3s5QJEkNzJUbyRnmAQUne6k04qFCrdocdRWDFk3OZaP1/5YdvytwBw+qgW725+42be8Ooe1203Az1jT4BiXL3X/OIFDtuThlTBWygCJSHsXKRn8PUIpJF/2WdBGzOuIr0i04yrpOXzkTqo=
  on:
    tags: true
    all_branches: true
