language: python
python:
- 2.6
- 2.7
script:
- pip install git+git://github.com/pyblish/pyblish-nuke.git
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: FKu7GA44wzGdEjet3kHMdyKuJYGLL05evGQmiUY2cDAF25by3kqE/TOPm96cBaLfaH0xRELk5SYTQgCZjhm3FJtd1sK6mx6/YtvOj/OWfjqKutnKDw6DRR2yUwPlqvmv9JPai7wRLD5HrkXOsnsVaKcs8fM50b7Cz03puaRoYHc=
  on:
    tags: true
    all_branches: true
    python: 2.6
